# Generated by Django 3.1.1 on 2020-10-15 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('state_code', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('main_phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='mirmir_app.statusfield')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
