# Generated by Django 3.1.1 on 2020-10-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirmir_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusfield',
            name='pretty_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
