# Generated by Django 3.1.1 on 2020-10-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirmir_app', '0005_auto_20201016_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('display_order', models.IntegerField()),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.RenameModel(
            old_name='SortFields',
            new_name='SortField',
        ),
    ]
