# Generated by Django 3.1.1 on 2020-10-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirmir_app', '0006_auto_20201016_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslide',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
