# Generated by Django 3.1.1 on 2020-10-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirmir_app', '0009_carouselslide_caption_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageWarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('show_warning', models.BooleanField(default=False)),
            ],
        ),
    ]
