# Generated by Django 3.1.1 on 2020-10-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirmir_app', '0010_mainpagewarning'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageHighlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='highlight_images')),
                ('text', models.TextField()),
            ],
        ),
    ]
