# Generated by Django 3.1.1 on 2020-10-20 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirmir_app', '0012_auto_20201019_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='mirmir_app.statusfield'),
        ),
    ]
