# Generated by Django 3.1.1 on 2020-10-21 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirmir_app', '0014_orderitemquantity_ordertype_paymentstatus_shippingstatus_transactiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('order_date', models.DateField(auto_now_add=True)),
                ('billing_birthdate', models.DateField(blank=True, null=True)),
                ('billing_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_company', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_address', models.CharField(max_length=100)),
                ('billing_address2', models.CharField(max_length=100)),
                ('billing_city', models.CharField(max_length=50)),
                ('billing_state_code', models.CharField(max_length=4)),
                ('billing_zip_code', models.IntegerField()),
                ('billing_email', models.EmailField(max_length=100)),
                ('shipping_birthdate', models.DateField(blank=True, null=True)),
                ('shipping_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_company', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_address', models.CharField(max_length=100)),
                ('shipping_address2', models.CharField(max_length=100)),
                ('shipping_city', models.CharField(max_length=50)),
                ('shipping_state_code', models.CharField(max_length=4)),
                ('shipping_zip_code', models.IntegerField()),
                ('gift_message', models.CharField(max_length=1024)),
                ('sub_total', models.FloatField()),
                ('order_notes', models.CharField(max_length=1024)),
                ('handling', models.FloatField()),
                ('shipping', models.FloatField()),
                ('tax', models.FloatField()),
                ('total', models.FloatField()),
                ('previous_order_number', models.IntegerField(blank=True, null=True)),
                ('is_pickup', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('shipping_service', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_tracking_number', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='mirmir_app.contact')),
                ('order_items', models.ManyToManyField(related_name='orders', to='mirmir_app.OrderItemQuantity')),
                ('order_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='mirmir_app.ordertype')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='mirmir_app.paymentstatus')),
                ('shipping_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='mirmir_app.shippingstatus')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='mirmir_app.transactiontype')),
            ],
        ),
    ]
