# Generated by Django 3.1.1 on 2020-10-21 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirmir_app', '0018_auto_20201021_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='mirmir_app.paymentstatus'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='mirmir_app.shippingstatus'),
        ),
    ]
