# Generated by Django 3.1.1 on 2020-10-21 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirmir_app', '0019_auto_20201021_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_company',
            field=models.CharField(default="Mirmir's Well Meadery", max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_email',
            field=models.EmailField(default='mirmirswellmeadery@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_state_code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_zip_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='mirmir_app.contact'),
        ),
        migrations.AlterField(
            model_name='order',
            name='gift_message',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='order',
            name='handling',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_notes',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='mirmir_app.ordertype'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='mirmir_app.paymentstatus'),
        ),
        migrations.AlterField(
            model_name='order',
            name='previous_order_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_service',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_state_code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='mirmir_app.shippingstatus'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_tracking_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_zip_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='sub_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='mirmir_app.transactiontype'),
        ),
        migrations.AlterField(
            model_name='orderitemquantity',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mirmir_app.order'),
        ),
    ]
