# Generated by Django 3.1.1 on 2020-10-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirmir_app', '0021_productphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphoto',
            name='photo',
            field=models.ImageField(upload_to='product_images'),
        ),
    ]
