# Generated by Django 3.1.1 on 2020-10-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirmir_app', '0023_auto_20201022_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_birthdate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_state_code',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_zip_code',
            field=models.IntegerField(blank=True),
        ),
    ]
