# Generated by Django 3.1.1 on 2020-10-26 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirmir_app', '0024_auto_20201026_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='mirmir_app.contact'),
        ),
    ]
