# Generated by Django 3.1.1 on 2020-10-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirmir_app', '0026_auto_20201026_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date']},
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_birthdate',
            field=models.DateField(blank=True),
        ),
    ]
