# Generated by Django 3.1.1 on 2020-11-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirmir_app', '0029_auto_20201101_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_company',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
