# Generated by Django 3.1.1 on 2020-11-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirmir_app', '0030_auto_20201102_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
