from django.urls import path
from . import views
from django.conf import settings

app_name = 'mirmir_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('main/', views.main, name='main'),
    path('about/', views.about, name='about'),
    path('mead_club/', views.club, name='club'),
    path('archive/', views.archive, name='archive'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('employee_main/', views.employee_main, name='employee_main'),
    path('main_page_management/', views.main_page_management,
         name='main_page_management'),
    path('highlights/', views.highlights, name='highlights'),
    path('get_warning/', views.get_warning, name='get_warning'),
    path('get_carousele/', views.get_carousele, name='get_carousele'),
    path('save_slide/', views.save_slide, name='save_slide'),
    path('save_highlight/', views.save_highlight, name='save_highlight'),
    path('save_warning/', views.save_warning, name='save_warning'),
    path('add_new_slide/', views.add_new_slide, name='add_new_slide'),
    path('execute_delete/', views.execute_delete, name='execute_delete'),
    path('save_new_highlight/', views.save_new_highlight,
         name='save_new_highlight'),
    path('profile/', views.profile, name='profile'),
    path('shop/', views.shop, name='shop'),
    path('shop_get_product_data/', views.shop_get_product_data,
         name='shop_get_product_data'),
    path('checkout/', views.checkout, name='checkout'),
    path('get_user_data_for_checkout/', views.get_user_data_for_checkout,
         name='get_user_data_for_checkout'),
    path('cart_verification/', views.cart_verification, name='cart_verification'),
    path('upsert_order/', views.upsert_order, name='upsert_order'),
    path('order_details/<int:order_num>/',
         views.order_details, name="order_details"),
    path('get_open_orders/', views.get_open_orders, name='get_open_orders'),
    path('save_order_changes/', views.save_order_changes,
         name='save_order_changes'),
    path('get_next_order_number_employee/', views.get_next_order_number_employee,
         name='get_next_order_number_employee'),
    path('get_active_products/', views.get_active_products,
         name='get_active_products'),
    path('save_product_changes/', views.save_product_changes,
         name='save_product_changes'),
    path('save_photo/', views.save_photo, name='save_photo'),
    path('send_new_code/', views.send_new_code, name='send_new_code'),
    path('confirm/', views.confirm, name='confirm'),
    path('email_sent/', views.email_sent, name='email_sent'),
    path('send_email/', views.send_email, name='send_email'),
    path('send_customer_email/', views.send_customer_email,
         name='send_customer_email'),
    path('confirm_login/', views.confirm_login, name='confirm_login'),
    path('reset_password_request/', views.reset_password_request,
         name='reset_password_request'),
    path('change_password/', views.change_password, name='change_password'),
    path('logged_in_password_reset/', views.logged_in_password_reset,
         name='logged_in_password_reset'),
]
